language: node_js
env:
- CXX=g++-4.8
os:
- linux
- osx
node_js:
#- '0.10'
#- '0.12'
#- 4
#- 5
#- 6
#- 7
- 8
- 9
- 10

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
sudo: false
before_install:
- if [[ $TRAVIS_OS_NAME == "osx" ]]; then export CXX=clang; fi
# related: https://github.com/travis-ci/travis-ci/issues/6307#issuecomment-350725425
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; command curl -sSL https://rvm.io/mpapis.asc | gpg --import -; then rvm get stable; fi
- $CXX --version

- PUBLISH_BINARY=false
- echo $TRAVIS_BRANCH
- echo `git describe --tags --always HEAD`

- case ${TRAVIS_NODE_VERSION} in 0.8*|0.10*) npm install -g npm@2 ;; esac
- npm config set progress false
- npm config set spin false
- npm install -g node-gyp node-pre-gyp
install:
- npm install --build-from-source
before_deploy:
- node-pre-gyp package 2>&1
deploy:
  provider: releases
  api_key:
    secure: vzDC4A3BtVkblWvKzmmslHMGVpGOiP0OJIYJytia0rPV5gxjOsHCcBkogosgSyyp40v9Lk0iFMH3BFLxrEgleudfRdgTaOExdC0FNmf9FtEPjLW3nLkcKzvK4L9+XO3/OIUSU0Aw3d7dakboi04nXavMwHfywQGM4+isKwuQMoh38zGrJfhGuwtENmLzn6E550HzFFJFWmqlsBmZlFt50Jxsm/pG8HsQ2IYd4/ILTq7TsgcGiifiXaMwMucbLKxNAKOh6g+9DqlRyyg7d6ptWR2PcVe4PAaVmH7UhElEON81BkqfODWgxZjSYx6FQgnlGeq3RXrKXhuagaqCdhgJiJR004dwTaBQzjDqYCdMEoUQcoOF5dvkNFWcIk2qk6OlWrCJqiC5l6nbHk+SeuBLuDvXv/2hl2N3QCaNs8C3tCCUps/sAQUF4r9cChFSFkcqzlKAzTQJ2TPHEmOtN/36JKoo1w3ZJrtCUX7TfgftBGjn4g4sLYMCww7/8duRKtm0VbYiRSQ9hcJ2ufXfosSMkPkQXLNFab/QYt6Fp6RKzVAlMf5Fk7twLMHLv/EW5yAh6EB+kOTfDgP9QbZBfO1LcEsV5TtqhdgeHr4pB7BrFHxoSvvthnQ90Pzc5EJUZOpwPTYdemQer4pMjeL9+8KK8Nv/prJ4B+VWx4inqamMOUc=
  file: build/stage/libxmljs/libxmljs/releases/download/**/*.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
